import post1 from "../public/01.png";
import post2 from "../public/02.png";
import post3 from "../public/03.png";
import post4 from "../public/04.png";
import img1 from "../public/img1-min.png";
import img2 from "../public/img2-min.png";
import img3 from "../public/img3-min.png";
import img4 from "../public/img4-min.png";
import img5 from "../public/img5-min.png";
import img6 from "../public/img6-min.png";
import img7 from "../public/img7-min.png";
import img8 from "../public/img8-min.png";
import img9 from "../public/img9-min.png";
import img10 from "../public/img10-min.jpg";
import img11 from "../public/img11-min.jpg";
import img12 from "../public/img12-min.jpg";
import img13 from "../public/img13-min.jpeg";
import img14 from "../public/img14-min.jpg";
import img15 from "../public/img15-min.jpg";
import img16 from "../public/img16-min.jpg";
import img17 from "../public/img17-min.jpg";
import img18 from "../public/img18-min.jpg";
import img19 from "../public/img19-min.jpg";
import img20 from "../public/img20-min.jpg";
import img21 from "../public/img21-min.jpg";
import img22 from "../public/img22-min.jpg";
import img23 from "../public/img23-min.jpg";
import img24 from "../public/img24-min.jpg";
import img25 from "../public/img25-min.jpg";
import img26 from "../public/img26-min.jpg";
import img27 from "../public/img27-min.jpg";
import img28 from "../public/img28-min.png";
import img29 from "../public/img29-min.jpg";
import img30 from "../public/img30-min.jpg";
import img31 from "../public/img31-min.png";
import img32 from "../public/img32-min.jpg";
import img33 from "../public/img33-min.jpg";
import img34 from "../public/img34-min.jpg";
import img35 from "../public/img35-min.jpg";
import img36 from "../public/img36-min.png";

export const data = [
  {
    id: 1,
    name: "Barberton Daisy",
    desc:
      "The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. ",
    size: "m",
    rating: 3,
    review: 10,
    price: 23,
    category: "house plants",
    tags: "house,plants,flowers",
    sku: 12342124,
    img: img1,
  },
  {
    id: 2,
    name: "Angel Wing Begonia",
    desc:
      "The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. ",
    size: "s",
    rating: 5,
    review: 14,
    price: 26,
    category: "Potter plants",
    tags: "potter,plants,flowers",
    img: img2,
    sku: 12312124,
  },
  {
    id: 3,
    name: "African Violet",
    desc: "",
    size: "m",
    rating: 4,
    review: 17,
    price: 32,
    category: "seeds",
    img: img3,
    tags: "seed,plants,flowers",
    sku: 12342124,
  },
  {
    id: 4,
    name: "Beach Spider Lily",
    desc: "",
    size: "l",
    rating: 5,
    review: 11,
    price: 20,
    category: "small plants",
    tags: "samall,plants,flowers",
    img: img4,
    sku: 12342123124,
  },
  {
    id: 5,
    name: "Aluminum Plant",
    desc: "",
    size: "s",
    rating: 4,
    review: 13,
    img: img5,
    price: 23,
    category: "big plants",
    tags: "big,plants,flowers",
    sku: 12342124,
  },
  {
    id: 6,
    name: "Bird's Nest Fern",
    desc: "",
    size: "xl",
    rating: 4,
    review: 10,
    price: 23,
    img: img6,
    category: "succelents",
    tags: "succelents,plants,flowers",
    sku: 12342124,
  },
  {
    id: 7,
    name: "Angel Wing Begonia",
    desc: "",
    size: "m",
    rating: 5,
    review: 15,
    price: 27,
    category: "trerrariums",
    img: img7,
    tags: "trerrariums,plants,flowers",
    sku: 12342124,
  },
  {
    id: 8,
    name: "Broadleaf Lady Palm",
    desc: "",
    size: "s",
    rating: 4,
    review: 12,
    price: 30,
    img: img8,
    category: "gardening",
    tags: "gardening,plants,flowers",
    sku: 12342124,
  },
  {
    id: 9,
    name: "Aluminum Plant",
    desc: "",
    size: "l",
    rating: 5,
    img: img9,
    review: 18,
    price: 43,
    category: "accessories",
    tags: "accessories",
    sku: 12342124,
  },
  {
    id: 10,
    name: "Blushing Bromeliad",
    desc: "",
    size: "xl",
    rating: 5,
    review: 16,
    price: 320,
    category: "seed",
    img: img10,
    tags: "seed,flowers",
    sku: 12342124,
  },
  {
    id: 11,
    name: "Beach Spider Lily",
    desc: "",
    size: "m",
    rating: 5,
    review: 19,
    price: 230,
    category: "big plants",
    img: img11,
    tags: "big plants",
    sku: 12342124,
  },
  {
    id: 12,
    name: "Aluminum Plant",
    desc: "",
    size: "s",
    rating: 5,
    review: 20,
    price: 200,
    category: "potter plans",
    img: img12,
    tags: "potter,flowers,plants",
    sku: 12342124,
  },
  {
    id: 13,
    name: "Beach Spider Lily",
    desc: "",
    size: "l",
    rating: 5,
    review: 43,
    price: 23,
    category: "small plants",
    tags: "",
    img: img13,
    sku: 12342124,
  },
  {
    id: 14,
    name: "Chinese Evergreen",
    desc: "",
    size: "m",
    rating: 4,
    review: 32,
    price: 130,
    img: img14,
    category: "small plants",
    tags: "small,plants,flowers",
    sku: 12342124,
  },
  {
    id: 15,
    name: "African Violet",
    desc: "",
    size: "l",
    img: img15,
    rating: 5,
    review: 21,
    price: 270,
    category: "succulents",
    tags: "succulents,plants,flowers",
    sku: 12342124,
  },
  {
    id: 16,
    name: "Barberton Daisy",
    desc:
      "The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. ",
    size: "m",
    rating: 3,
    review: 10,
    price: 23,
    category: "house plants",
    tags: "house,plants,flowers",
    sku: 12342124,
    img: img16,
  },
  {
    id: 17,
    name: "Angel Wing Begonia",
    desc:
      "The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. ",
    size: "s",
    rating: 5,
    review: 14,
    price: 26,
    category: "Potter plants",
    tags: "potter,plants,flowers",
    img: img17,
    sku: 12312124,
  },
  {
    id: 18,
    name: "African Violet",
    desc: "",
    size: "m",
    rating: 4,
    review: 17,
    price: 32,
    category: "seeds",
    img: img18,
    tags: "seed,plants,flowers",
    sku: 12342124,
  },
  {
    id: 19,
    name: "Beach Spider Lily",
    desc: "",
    size: "l",
    rating: 5,
    review: 11,
    price: 20,
    category: "small plants",
    tags: "samall,plants,flowers",
    img: img19,
    sku: 12342123124,
  },
  {
    id: 20,
    name: "Aluminum Plant",
    desc: "",
    size: "s",
    rating: 4,
    review: 13,
    img: img20,
    price: 23,
    category: "big plants",
    tags: "big,plants,flowers",
    sku: 12342124,
  },
  {
    id: 21,
    name: "Bird's Nest Fern",
    desc: "",
    size: "xl",
    rating: 4,
    review: 10,
    price: 23,
    img: img21,
    category: "succelents",
    tags: "succelents,plants,flowers",
    sku: 12342124,
  },
  {
    id: 22,
    name: "Angel Wing Begonia",
    desc: "",
    size: "m",
    rating: 5,
    review: 15,
    price: 27,
    category: "trerrariums",
    img: img22,
    tags: "trerrariums,plants,flowers",
    sku: 12342124,
  },
  {
    id: 23,
    name: "Broadleaf Lady Palm",
    desc: "",
    size: "s",
    rating: 4,
    review: 12,
    price: 30,
    img: img23,
    category: "gardening",
    tags: "gardening,plants,flowers",
    sku: 12342124,
  },
  {
    id: 24,
    name: "Aluminum Plant",
    desc: "",
    size: "l",
    rating: 5,
    img: img24,
    review: 18,
    price: 43,
    category: "accessories",
    tags: "accessories",
    sku: 12342124,
  },
  {
    id: 25,
    name: "Blushing Bromeliad",
    desc: "",
    size: "xl",
    rating: 5,
    review: 16,
    price: 320,
    category: "seed",
    img: img25,
    tags: "seed,flowers",
    sku: 12342124,
  },
  {
    id: 26,
    name: "Beach Spider Lily",
    desc: "",
    size: "m",
    rating: 5,
    review: 19,
    price: 230,
    category: "big plants",
    img: img26,
    tags: "big plants",
    sku: 12342124,
  },
  {
    id: 27,
    name: "Aluminum Plant",
    desc: "",
    size: "s",
    rating: 5,
    review: 20,
    price: 200,
    category: "potter plans",
    img: img27,
    tags: "potter,flowers,plants",
    sku: 12342124,
  },
  {
    id: 28,
    name: "Beach Spider Lily",
    desc: "",
    size: "l",
    rating: 5,
    review: 43,
    price: 23,
    category: "small plants",
    tags: "",
    img: img28,
    sku: 12342124,
  },
  {
    id: 29,
    name: "Chinese Evergreen",
    desc: "",
    size: "m",
    rating: 4,
    review: 32,
    price: 130,
    img: img29,
    category: "small plants",
    tags: "small,plants,flowers",
    sku: 12342124,
  },
  {
    id: 30,
    name: "African Violet",
    desc: "",
    size: "l",
    img: img30,
    rating: 5,
    review: 21,
    price: 270,
    category: "succulents",
    tags: "succulents,plants,flowers",
    sku: 12342124,
  },
  {
    id: 31,
    name: "Barberton Daisy",
    desc:
      "The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. ",
    size: "m",
    rating: 3,
    review: 10,
    price: 23,
    category: "house plants",
    tags: "house,plants,flowers",
    sku: 12342124,
    img: img31,
  },
  {
    id: 32,
    name: "Angel Wing Begonia",
    desc:
      "The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. ",
    size: "s",
    rating: 5,
    review: 14,
    price: 26,
    category: "Potter plants",
    tags: "potter,plants,flowers",
    img: img32,
    sku: 12312124,
  },
  {
    id: 33,
    name: "African Violet",
    desc: "",
    size: "m",
    rating: 4,
    review: 17,
    price: 32,
    category: "seeds",
    img: img33,
    tags: "seed,plants,flowers",
    sku: 12342124,
  },
  {
    id: 34,
    name: "Beach Spider Lily",
    desc: "",
    size: "l",
    rating: 5,
    review: 11,
    price: 20,
    category: "small plants",
    tags: "samall,plants,flowers",
    img: img34,
    sku: 12342123124,
  },
  {
    id: 35,
    name: "Aluminum Plant",
    desc: "",
    size: "s",
    rating: 4,
    review: 13,
    img: img35,
    price: 23,
    category: "big plants",
    tags: "big,plants,flowers",
    sku: 12342124,
  },
  {
    id: 36,
    name: "Bird's Nest Fern",
    desc: "",
    size: "xl",
    rating: 4,
    review: 10,
    price: 23,
    img: img36,
    category: "succelents",
    tags: "succelents,plants,flowers",
    sku: 12342124,
  },
  {
    id: 37,
    name: "Angel Wing Begonia",
    desc: "",
    size: "m",
    rating: 5,
    review: 15,
    price: 27,
    category: "trerrariums",
    img: img7,
    tags: "trerrariums,plants,flowers",
    sku: 12342124,
  },
  {
    id: 38,
    name: "Broadleaf Lady Palm",
    desc: "",
    size: "s",
    rating: 4,
    review: 12,
    price: 30,
    img: img8,
    category: "gardening",
    tags: "gardening,plants,flowers",
    sku: 12342124,
  },
  {
    id: 39,
    name: "Aluminum Plant",
    desc: "",
    size: "l",
    rating: 5,
    img: img9,
    review: 18,
    price: 43,
    category: "accessories",
    tags: "accessories",
    sku: 12342124,
  },
  {
    id: 40,
    name: "Blushing Bromeliad",
    desc: "",
    size: "xl",
    rating: 5,
    review: 16,
    price: 320,
    category: "seed",
    img: img10,
    tags: "seed,flowers",
    sku: 12342124,
  },
  {
    id: 41,
    name: "Beach Spider Lily",
    desc: "",
    size: "m",
    rating: 5,
    review: 19,
    price: 230,
    category: "big plants",
    img: img11,
    tags: "big plants",
    sku: 12342124,
  },
  {
    id: 42,
    name: "Aluminum Plant",
    desc: "",
    size: "s",
    rating: 5,
    review: 20,
    price: 200,
    category: "potter plans",
    img: img12,
    tags: "potter,flowers,plants",
    sku: 12342124,
  },
  {
    id: 43,
    name: "Beach Spider Lily",
    desc: "",
    size: "l",
    rating: 5,
    review: 43,
    price: 23,
    category: "small plants",
    tags: "",
    img: img1,
    sku: 12342124,
  },
  {
    id: 44,
    name: "Chinese Evergreen",
    desc: "",
    size: "m",
    rating: 4,
    review: 32,
    price: 130,
    img: img14,
    category: "small plants",
    tags: "small,plants,flowers",
    sku: 12342124,
  },
  {
    id: 45,
    name: "African Violet",
    desc: "",
    size: "l",
    img: img15,
    rating: 5,
    review: 21,
    price: 270,
    category: "succulents",
    tags: "succulents,plants,flowers",
    sku: 12342124,
  },
];

export const posts = [
  {
    id: 1,
    img: post1,
    title: "September 12  I Read in 6 minutes",
    desc: "Cacti are succulents are easy care plants for any home or patio. ",
    name: "Cactus & Succulent Care Tips",
  },
  {
    id: 2,
    img: post2,
    title: "September 13  I Read in 2 minutes",
    desc: "Best in hanging baskets. Prefers medium to high light.",
    name: "Top 10 Succulents for Your Home",
  },
  {
    id: 3,
    img: post3,
    title: "September 15  I Read in 3 minutes",
    desc: "Cacti and succulents thrive in containers and because most are..",
    name: "Cacti & Succulent  Care Tips",
  },
  {
    id: 4,
    img: post4,
    title: "September 15  I Read in 2 minutes",
    desc: "The benefits of houseplants are endless. In addition to..",
    name: "Best Houseplants  Room by Room",
  },
];
